### ISSUE TITLE
Shortcut search is alt+Q in code but alt+S in readme

### ISSUE THREAD

**Issue by emmadehaan** [RealP/evercuts#1]
Thanks for the repo, simple but such a nice addition. Planning on adding more shortcuts?

**Comment by RealP** [comment]
Fixed the readme! I'm not sure what other shortcuts are need? It's pretty straightforward to add some for
- Create new note
- Go to notes/notebooks/tags page

I can add those if you think they are helpful?

What I need is a feature to ctrl+click to open note in new tab.

**Comment by emmadehaan** [comment]
Those would be great! Possibly one which automatically opens the shortcuts side bar, allowing you to scroll through with arrows? 
A ctrl+click would be amazing, currently use a work around with a keyboard shortcut to a new tab in chrome to my default notebook in evernote, and then manually search and open the note i need. So, if you can solve that mystery i would be forever grateful.

**Comment by RealP** [comment]
I don't really use the shortcut sidebar all that much but I probably should. Right now it doesn't seem straightforward to implement so the efforts outweigh the benefits. I may revisit it if I ever start using shortcuts.

### I did add two new features.
1. __ALT+T__ Open note in new tab _(It opens the note that is currently focused, also opens in FS)_
2. __ALT+Click__ Open note in new window _(This is one is cooler, it opens the note in a new window.)_

ALT+T is kind of useless to me since I am trying to use the Evernote as an installed chrome application which doesn't allow tabs. The ALT+click is pretty sweet though!

**Comment by emmadehaan** [comment]
Understandable! Thanks for the new features
